In [0]:
import numpy as np

## Arrays and Vectorization

**Arrays** are sequences of same-type data points (most-often numbers).  Numpy allows us to work with the sequence without writing a for-loop, using a technique called **vectorization**.  

Besides an **array()** class, Numpy also includes a lot of math functions, which makes analysis much easier.  Let's try some out!

## Numpy Exercises

### Building Arrays

Numpy has some convenient array-building functions as well.  Some commonly-used are examples are **arange()**, **linspace()**, **zeros()**, and the random number generation functions in **random**.

| function | Purpose |  Example |
| :-----------: | :-------------: |
| **np.arange()**                  | Makes an array with all the integers between two values | np.arange(2, 7) |
| **np.linspace()**               | Makes a specific-length array |  np.linspace(2, 3, 10) |
| **np.zeros()**                    | Makes an array of all zeros | np.zeros(5) |
| **np.ones()**                     | Makes an array of all ones | np.ones(3) |
| **np.random.random()** | Makes an array of random numbers | np.random.random(100) |
| **np.random.randn()**     | Makes an array of normally-distributed random numbers | np.random.randn(100) |


1. Make an array containing the numbers 1 to 15.

2. Make an array containing 20 zeros.

3. Make an array contain 20 ones!

4. Generate an array of 10 random numbers from Numpy's **random** submodule, using any function you want.

## Statistics Methods on Arrays

Arrays have many useful math methods.  For example, to get the mean of an array of numbers:

```python
data = np.random.random(100)
data.mean()
```

**Exercise**: Calculate the statistics on the following numbers:

In [3]:
data = np.arange(2, 7)
data

array([2, 3, 4, 5, 6])

1. Get the mean of the data.

2. What is the sum of the data?

3. The maximum of the data?

4. The standard deviation of the data?

## Statistics Functions on Arrays

Numpy also has many useful statistics **functions**.  These take an array as an input and can be found inside the **np** library.  Sometimes, the same functionality can be found both as a Numpy function  and an array method, giving you the choice of how you'd like to use it.  


For example, the following **method**:


```python
data = np.random.random(100)
data.mean()
```

can also be used as a **function**:


```python
data = np.random.random(100)
np.mean(data)
```

**Exercise**: Calculate the statistics on the following numbers, this time using the **function** version of the previous methods.

In [0]:
data = np.arange(2, 7)
data

array([2, 3, 4, 5, 6])

1. Get the mean of the data.

2. What is the sum of the data?

3. What is the minimum of the data?

4. The standard deviation?

## Arithmetic with Arrays

Arrays can also be added, subtracted, multiplied, and divided.  

For example, to add 10 to all values in an array:

```python
data = np.random.randn(5)
print(data)
print(data + 10)
```

Here is multiplying two arrays together: 

```python
print(data )
print(data * data)
```



**Exercises**: Modify the following arrays using the math operators  (+, -, *, /)

In [7]:
data = np.arange(-3, 5)
data

array([-3, -2, -1,  0,  1,  2,  3,  4])

1. Multiply the data by 100

2. Add 40 to each value in the array.

3. Divide the numbers by 100

4. Subtract the data from itself.

## Extra Exercises

### Exercise: Other math functions

1. Calculate the square of all the numbers from 0 to 8.

2. Calculate the square roots of all the numbers from 0 to 8.

3. Make an array of 20 values, all of them 2's.

4. Subtract the mean of the array from each element in the array (a.k.a. "mean-centering" the values)

In [8]:
data = np.random.randn(20)
data

array([-0.52881442,  0.2053102 , -0.62343832,  1.6985349 ,  1.31156082,
        0.585077  , -1.4971368 , -0.58857981,  0.7222168 , -1.52160601,
       -2.1574803 , -0.47017442, -1.17701195,  0.24355345, -1.29298196,
       -0.12360317, -1.83561425, -0.49679985, -0.17241933,  1.43493667])

### Translating Algorithms into Code

Calculate the standard deviation of an array's values, without using the numpy.std() function.  (Formula can be found here: http://www.mathsisfun.com/data/standard-deviation-formulas.html)

1. Work out the Mean (the simple average of the numbers)
2. Then for each number: subtract the Mean and square the result
3. Then work out the mean of those squared differences.
4. Take the square root of that and we are done!


In [0]:
data = np.random.randn(100)
